plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/Season/FindEndorphin/工作/AI/codex/china3d-terrain-map"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]